### ISSUE TITLE
After creating the merkle_tree.json.... Not able to create newDistributor

### ISSUE THREAD

**Issue by anusriesto** [jito-foundation/distributor#13]
`./target/release/cli --mint ZdZED9GYzW41wSrydaqZJbsYFhprasmGHVTQF2725Db --rpc-url https://api.devnet.solana.com --keypair-path /home/anusriesto/.config/solana/id.json --program-id EesKdFLwf2QgP1CbHsxUT7UwSiPUbTEjNyLgsaa6xKnD new-distributor --clawback-receiver-token-account B1ExxqvnnUuKZUFZmw2sYSVMV8wZasX1cREnb79xp3tc --start-vesting-ts 1719458063 --end-vesting-ts 1719461663 --merkle-tree-path merkle_tree.json --clawback-start-ts 1719725512`

Passing the below argument to create new_distributor
Getting this error

Failed to create MerkleDistributor: Error { request: Some(SendTransaction), kind: RpcError(RpcResponseError { code: -32002, message: "Transaction simulation failed: Error processing Instruction 0: custom program error: 0x7de", data: SendTransactionPreflightFailure(RpcSimulateTransactionResult { err: Some(InstructionError(0, Custom(2014))), logs: Some(["Program EesKdFLwf2QgP1CbHsxUT7UwSiPUbTEjNyLgsaa6xKnD invoke [1]", "Program log: Instruction: NewDistributor", "Program 11111111111111111111111111111111 invoke [2]", "Program 11111111111111111111111111111111 success", "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [2]", "Program log: Create", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]", "Program log: Instruction: GetAccountDataSize", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1595 of 173103 compute units", "Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success", "Program 11111111111111111111111111111111 invoke [3]", "Program 11111111111111111111111111111111 success", "Program log: Initialize the associated token account", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]", "Program log: Instruction: InitializeImmutableOwner", "Program log: Please upgrade to SPL Token 2022 for immutable owner support", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 166490 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]", "Program log: Instruction: InitializeAccount3", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4214 of 162606 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success", "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 21990 of 180078 compute units", "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success", "Program log: AnchorError occurred. Error Code: ConstraintTokenMint. Error Number: 2014. Error Message: A token mint constraint was violated.", "Program EesKdFLwf2QgP1CbHsxUT7UwSiPUbTEjNyLgsaa6xKnD consumed 46213 of 200000 compute units", "Program EesKdFLwf2QgP1CbHsxUT7UwSiPUbTEjNyLgsaa6xKnD failed: custom program error: 0x7de"]), accounts: None, units_consumed: Some(46213), return_data: None }) }) }

**Comment by Tinabates** [comment]
Thx 🙏

**Comment by Tinabates** [comment]
I’m not using ledger on this one
